import { Platform, StyleSheet, Dimensions } from 'react-native';
import { colors } from './theme';

const width = Dimensions.get('window').width;
const height = Dimensions.get('window').height;

const styles = StyleSheet.create({
  checkboxContainer: {
    borderWidth: 0,
    backgroundColor: 'transparent',
    width: '100%',
    padding: 5,
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: colors.white,
  },
  introContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: '#9f5dbc',
    height: 230,
  },
  backImageOfIntroContainer: {
    flex: 1,
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  skipnowText: {
    color: 'white',
    fontFamily: 'Roboto',
    fontSize: 12,
  },
  dayText: {
    color: colors.white,
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: 16,
  },
  tabTitle: {
    color: '#9f5dbc',
    fontFamily: 'Roboto',
    fontSize: 13,
    marginTop: 5,
  },
  introPrgText: {
    color: colors.white,
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: 25,
    marginTop: 20,
    backgroundColor: colors.transparent,
  },
  beginContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: colors.white,
    marginTop: 30,
    borderRadius: 18,
  },
  playArrow: {
    margin: 8,
    marginLeft: 12,
  },
  beginText: {
    marginTop: Platform.OS === 'ios' ? 8 : 6,
    marginRight: 16,
    color: colors.black,
    fontSize: 13,
    fontFamily: 'Roboto',
  },
  dailyQuotesContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: colors.white,
    margin: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0,
    shadowRadius: 2,
    elevation: 1,
    borderColor: colors.grey200,
    borderWidth: 1,
    borderRadius: 2,
  },
  personalizedContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: colors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0,
    shadowRadius: 2,
    elevation: 1,
    borderColor: colors.grey200,
    borderWidth: 1,
    borderRadius: 2,
    height: Dimensions.get('window').height - (Dimensions.get('window').height * 0.3),
  },
  hideView: {
    display: 'none',
  },
  quotesTitleText: {
    color: '#3c4b65',
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: 14,
    marginTop: 15,
    backgroundColor: colors.transparent,
  },
  personalizedTitleText: {
    color: 'white',
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: 25,
    marginTop: 15,
    backgroundColor: colors.transparent,
  },
  seperator: {
    justifyContent: 'center',
    backgroundColor: colors.grey100,
    height: 1,
    width: '70%',
    marginTop: 5,
    marginBottom: 10,
    marginLeft: 10,
    marginRight: 10,
  },
  upperSeperator: {
    marginTop: 15,
    marginBottom: 15,
    marginLeft: 10,
    marginRight: 10,
  },
  bottomSeperator: {
    marginTop: 15,
    marginBottom: 15,
    marginLeft: 10,
    marginRight: 10,
  },
  seperatorPersonalized: {
    justifyContent: 'center',
    backgroundColor: colors.grey100,
    height: 1,
    width: '70%',
    marginTop: 10,
    marginBottom: 5,
    marginLeft: 10,
    marginRight: 10,
  },
  quotesSubText: {
    color: '#9c9c9c',
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: 14,
    margin: 10,
    backgroundColor: colors.transparent,
  },
  categoryContainer: {
    flex: 1,
    backgroundColor: colors.white,
  },
  categoryTitle: {
    color: '#3c4b65',
    fontFamily: 'Roboto',
    fontSize: 14,
    backgroundColor: colors.transparent,
    // fontWeight: 'bold',
  },
  categoryInnerContainer: {
    backgroundColor: colors.transparent,
    height: 20,
    flexDirection: 'row',
    marginTop: 20,
    marginBottom: 10,
  },
  diveContainer: {
    backgroundColor: colors.white,
    height: 110,
    margin: 25,
    marginTop: 10,
  },
  diveInnerContainer: {
    backgroundColor: colors.white,
  },
  subscribeText: {
    color: '#3c4b65',
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontSize: 20,
    marginLeft: 35,
    marginTop: 35,
    marginRight: 35,
    backgroundColor: colors.transparent,
  },
  listView: {
    backgroundColor: colors.transparent,
  },
  listViewContainer: {
    height: 110,
    width: 110,
  },
  listViewText: {
    color: colors.white,
    fontSize: 14,
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    backgroundColor: colors.transparent,
  },
  listViewSubText: {
    color: colors.white,
    fontSize: 13,
    textAlign: 'center',
    fontFamily: 'Roboto',
    marginTop: 5,
  },
  SubCategoryList: {
    backgroundColor: colors.white,
    paddingHorizontal: '5%',
    alignSelf: 'stretch',
  },
  MainList: {
    flex: 1,
    marginBottom: 5,
  },
  MainListText: {
    color: colors.grey800,
    fontSize: 16,
    marginTop: 20,
    marginBottom: 20,
    letterSpacing: 3,
  },
  FlatListViewStyle: {
    backgroundColor: 'white',
    height: 150,
  },
  FlatCustomListViewStyle: {
    backgroundColor: 'white',
  },
  FlatListImage: {
    height: 130,
    width: 130,
    justifyContent: 'center',
    alignItems: 'center',
  },
  FlatListTitle: {
    color: colors.white,
    fontSize: width > 400 ? 18 : 16,
    textAlign: 'center',
    fontFamily: 'Roboto',
    fontWeight: 'bold',
    marginBottom: 5,
  },
  FlatListText: {
    color: colors.white,
    fontSize: width > 400 ? 16 : 13,
    textAlign: 'center',
    fontFamily: 'Roboto',
    padding: 10,
  },
  FlatCustomListImage: {
    height: (Dimensions.get('window').width - (Dimensions.get('window').width * 0.1)) / 3,
    width: (Dimensions.get('window').width - (Dimensions.get('window').width * 0.1)) / 3,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 10,
  },
  FlatListCustomTitle: {
    color: colors.white,
    fontSize: 13,
    textAlign: 'center',
    fontFamily: 'Roboto',
    // fontWeight: 'bold',
  },
  FlatListCustomText: {
    color: colors.white,
    fontSize: 11,
    textAlign: 'center',
    fontFamily: 'Roboto',
    marginTop: 5,
    // opacity: 0.68,
    fontWeight: 'bold',
  },
  content:
  {
    height: '100%',
    width: '100%',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  containermodal: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    height: '20%',
  },
  innerContainer: {
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: '#fff',
    padding: 18,
    height: '20%',
  },
  btnTxt: {
    fontSize: 18,
    color: 'rgba(0, 0, 0, 0.5)',
  },
  btnTxtPersonalized: {
    fontSize: 15,
    color: 'white',
  },
  boxTitle1: {
    color: 'black',
    fontSize: 20,
    textAlign: 'center',
  },
  title:
  {
    fontSize: 18,
    color: 'black',
    textAlign: 'center',
  },
  tchblebtn: {
    marginTop: 20,
  },
  button: {
    borderRadius: 8,
    backgroundColor: '#7dd3d5',
    justifyContent: 'center',
    paddingVertical: 4,
    paddingHorizontal: 10,
    color: '#a25ad6',
  },
  buttonPersonalized: {
    borderRadius: 5,
    backgroundColor: '#7dd3d5',
    paddingVertical: 8,
    paddingHorizontal: 40,
    color: '#a25ad6',
  },
  popcontainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
    position: 'relative',
  },
  backImage: {
    flex: 1,
    width: '100%',
    height: '100%',
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer: {
    backgroundColor: 'transparent',
    marginTop: 50,
  },
  topText: {
    fontSize: 18,
    color: 'white',
    fontFamily: 'Roboto',
    textAlign: 'center',
    marginBottom: 5,
  },
  hedertxt: {
    fontSize: 12,
    color: 'white',
    textAlign: 'center',
    marginBottom: 20,
    fontStyle: 'italic',
  },
  centerContainer: {
    flex: 1,
    backgroundColor: 'transparent',
    marginLeft: 20,
  },
  bottomContainer: {
    bottom: 0,
    justifyContent: 'center',
    width: '100%',
    marginBottom: 50,
  },
  popinnerContainer: {
    borderRadius: 8,
    backgroundColor: 'transparent',
    paddingLeft: 20,
    paddingRight: 20,
    height: '100%',
    width: '100%',
  },
  headingtext: {
    fontSize: 18,
    color: colors.black,
    letterSpacing: 2,
    paddingRight: 9,
    textAlign: 'center',
    marginBottom: 10,
  },
  chk: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ecf0f1',
  },
  closebtn: {
    height: 20,
    width: 20,
    alignSelf: 'flex-end',
    marginTop: height > 750 ? 40 : 20,
  },
  image: {
    height: 20,
    width: 20,
  },
});

export const learnMoreButtonStyles = StyleSheet.create({
  text: {
    fontSize: 11,
    color: '#9f5dbc',
    fontFamily: 'Roboto',
    fontStyle: 'italic',
    textAlign: 'center',
    marginBottom: 0,
    width: '100%',
  },
  container: {
    height: 20,
    width: '100%',
    backgroundColor: colors.transparent,
  },
});

export const nextButtonStyles = StyleSheet.create({
  text: {
    fontSize: 20,
    color: 'white',
  },
  container: {
    height: 40,
    backgroundColor: colors.transparent,
    alignSelf: 'center',
    width: '70%',
    borderRadius: 50,
    borderColor: 'white',
    borderWidth: 1,
  },
});

export const buttonStyles = StyleSheet.create({
  text: {
    fontSize: 14,
    color: colors.white,
    fontWeight: 'bold',
    fontFamily: 'Roboto',
  },
  container: {
    flex: 1,
    marginTop: 20,
    marginBottom: 35,
    height: Platform.OS === 'ios' ? 40 : 45,
    backgroundColor: '#7dd3d5',
    justifyContent: 'center',
  },
});

export default styles;
