# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiveThru' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DiveThru
  pod 'Firebase/Messaging'

  target 'DiveThru-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'RNIap', :path => '../node_modules/react-native-iap'

  end

  target 'DiveThruTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
