# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiveThru' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DiveThru
  pod 'Firebase/Messaging'

  target 'DiveThru-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'react-native-calendar-events', :path => '../node_modules/react-native-calendar-events'

    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'RNIap', :path => '../node_modules/react-native-iap'

    pod 'RNShare', :path => '../node_modules/react-native-share'

    pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

    pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

    pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'

    pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

    pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  end

  target 'DiveThruTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
